
- name: Install pubtool Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - python3
    - python3-pip
    - python-virtualenv
    - uwsgi
    - uwsgi-plugin-python3
    - nginx
    - git
    - memcached
    - supervisor

- name: Python virtualenv
  command: virtualenv /usr/lib/olaf/ -p python3.4 creates="/usr/lib/dgu-pubtool/"
