
- name: Install pubtool Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - python3
    - python3-pip
    - python-virtualenv
    - uwsgi
    - uwsgi-plugin-python3
    - nginx
    - git
    - memcached
    - supervisor

- name: Python virtualenv
  command: virtualenv /usr/lib/dgu/pubtool/ -p python3.5 creates="/usr/lib/dgu/pubtool/"

- name: Python packages
  pip: requirements=/home/ubuntu/apps/pubtool/requirements/dev.txt virtualenv=/usr/lib/dgu/pubtool
  notify:
  - restart uWSGI

- name: uWSGI config file
  template: src=files/pubtool-uwsgi.ini
            dest=/etc/uwsgi/apps-enabled/pubtool.ini
            owner=root
            group=root
            mode=0644
  notify:
  - restart uWSGI

- name: Remove default nginx config file
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: nginx config file
  template: src=files/pubtool-nginx.conf dest=/etc/nginx/sites-enabled/pubtool.conf owner=root group=root mode=0644
  notify:
  - restart nginx

- name: Start services
  service: name={{ item }} state=started
  with_items:
    - nginx
    - uwsgi
